### ISSUE TITLE
Enable to validate emails

### ISSUE THREAD

**Issue by DrinKaziu** [dillingham/nova-items-field#16]
Any idea why I can show emails from my database but can't validate? Here is my code.. Sorry it's not much to go off of but I'm not sure what else to include. I'm not getting any error messages..

```php
Items::make('Recipients', 'credentials->emails')
         ->rules([
                'credentials->emails.*' => 'email|min:10',
          ])
         ->placeholder('Add new email'),
```

Thanks!

**Comment by dillingham** [comment]
Im going to venture a guess that the json mysql syntax has something to do with it
I haven't used this package with nested json columns like that
Does `'credentials.emails.*' => 'email|min:10',` work?

Closing only cause its a question, I'll keep an eye on this thread though.

**Comment by DrinKaziu** [comment]
It didn't work but now I know what the issue is and I can work with that :) Thanks so much for the quick response!  

In case you were wondering, here is what the sql credentials row looks like.. 
```sql
{"emails":["user@email.com","client@customer.com"]}
```

**Comment by DrinKaziu** [comment]
In case someone runs into the same situation, I was able to make it work by changing the 'credentials' cast from 'array' to 'collection in the model..

```php
public $casts = [
        'credentials' => 'collection'
    ];
```
Thanks again for all your help!

**Comment by ahmed1515** [comment]
@DrinKaziu, Still unable to validate

```
Items::make('Options', 'options->l1')->rules([
          'options->l1.*' => 'email',
])->onlyOnForms(),
```

And in model
```
protected $casts = [
        'options' => 'collection',
 ];
```
