### ISSUE TITLE
Field Doesnt Shown (Laravel 7.0, Nova 3.0)

### ISSUE THREAD

**Issue by kayacekovic** [dillingham/nova-items-field#17]
Hi, items field doesn't shown on creating page.

My model $casts
```
protected $casts = [
'campaign_info_texts' => 'array'
];
```

My nova resource
```
Items::make('Kampanya Bilgilendirme Açıklamları', 'campaign_info_texts')
          ->placeholder('Kampanya Bilgilendirme Açıklaması')
          ->createButtonValue('Ekle')
          ->listFirst(true)
          ->draggable()
          ->max(15),
```

Nova create resource
![Screenshot_2](https://user-images.githubusercontent.com/32109756/79694238-c1a8b680-8277-11ea-862c-5df4783099df.png)

But fields doesn't shown on creating page.

**Comment by Dandula** [comment]
+1

**Comment by sicbe** [comment]
I'm having the same problem. It used to work but I updated with composer yesterday and the field doesn't show anymore. Any solutions yet?

**Comment by dillingham** [comment]
@sicbe I just tested it and its working. Can you provide more info?

**Comment by dillingham** [comment]
Closing this until someone can help me reproduce.
