### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by ahmed1515** [dillingham/nova-items-field#22]
Required validation is't working.

**Comment by ahmed1515** [comment]
```
Items::make('Options', 'options->l1')->rules([
        'options.l1.*' => 'required|array|min:3',
])->onlyOnForms(),
```

Data format:
`option->{"l1":["yes","no"]}`

**Comment by dillingham** [comment]
Change it to dot notation instead of arrows and check out this issue. 


https://github.com/dillingham/nova-items-field/issues/16
