### ISSUE TITLE
REQUEST: Autocomplete values

### ISSUE THREAD

**Issue by vernard** [dillingham/nova-items-field#7]
Hi Brian!

Great package, btw. It's been very helpful to me.

I'm trying to add a functionality where I could type a few letters, then trigger an autocomplete?

Specifically, import this vue component: https://github.com/paliari/v-autocomplete

One way to do it is add meta parameters that:
- Tells if the items should use autocomplete component
- Specify the api route/url
- Specify what value of the searched object will be saved on the item field

Is this something that aligns with the objective of this package?

**Comment by dillingham** [comment]
Hi @vernard,

I do think having a belongs to field support would address a lot of scenarios for people and be the most fitting way to add Ajax search support BelongsTo::make()->searchable(). 

Items::make(‘Users’, ‘user_array’)->belongsTo(‘App\Nova\User’)

saving($model)

$model->user_array // [1,2,3,4,5] 

Would that accomplish your need?

Currently working on associative array support & validation though.

**Comment by vernard** [comment]
@dillingham yep, this would definitely work

**Comment by dillingham** [comment]
Im going to keep this as a static array field for now,  but thanks for the input
